config/routes.rb
Rails.application.routes.draw do
    root 'tweets#index'
    resources :tweets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    def index
        @tweets = Tweet.all
    end
    
    def show
        @tweet = Tweet.find(params[:id])
    end
    
    def new
        @tweet = Tweet.new
    end
    
    def create
        tweet = Tweet.new(message: params[:tweet][:message])
        tweet.save
        redirect_to '/'
    end
    
    def destroy
        tweet = Tweet.find(params[:id])
        tweet.destroy
        redirect_to '/'
    end
    
    def edit
        @tweet = Tweet.find(params[:id])
    end
    
    def update
        @tweet = Tweet.find(params[:id])
        @tweet = Tweet.update(message: params[:tweet][:message])
        redirect_to '/'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/hf/_header.html.erb
<div class="prf1">
  <%= image_tag '1500x500.jpg', height: '100%'%>
  <div class="prf2">
    <%= image_tag 'kindai.jpg', width: '200px'%>
  </div>
</div>

app/views/hf/_side.html.erb
<h2>近畿大学</h2>
<a href="#">@kindaiPR</a>

<p>近畿大学のTwitter公式アカウントです。
  気象警報による休講情報や、お得なランチ情報など、大学に関する情報を発信します。
  マグロに関するツイート多め🐟学生のみなさんの相談に乗りますので、くだらないことも気軽に話しかけてください。
  履修に関するご質問は所属学部。入試に関するご相談は、入学センターへお問い合わせ下さい。</p>
<p>大阪府東大阪市</p>
<p><%= link_to '新規ツイート', new_tweet_path, class: 'btn btn-info' %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div class="app-title nav-bar navbar-expend-md navbar-light">
        <div class="navbar-brand">Twitter</div>
      </div>
      <div class="header">
        <%= render "hf/header" %>
      </div>
        <% if flash.notice.present? %>
          <div class="alert alert-success" role="alert">
            <%= flash.notice %>
            <% end %>
          </div>
        <div class="con">
            <div class="side">
            <%= render "hf/side" %>
            </div>
          <div class="main" ><%= yield %></div>
        </div>

  </body>
</html>

app/views/tweets/edit.html.erb
<h1>編集</h1>
<p>
    <%= form_for @tweet , url: {action: :update} do |f| %>
    <%= f.text_area :message, :size =>"50x5" %>
    <%= f.submit '決定' %>
<% end %>
</p>

app/views/tweets/index.html.erb
<div class="main">
<h1>ツイート欄</h1>

<% @tweets.each do |twi| %>
    <p>
        <%= simple_format(twi.message) %>
        <time datetime="<%= twi.created_at %>">
        <%= twi.created_at %>
        <%= link_to '編集', "tweets/#{twi.id}/edit" %>
        <%= link_to '削除', "tweets/#{twi.id}", method: :delete %><br>
    </p>
<% end %>
</div>

app/views/tweets/new.html.erb
<h1>新規ツイート</h1>
<p>
    <%= form_for @tweet , url: {action: :create} do |f| %>
    <%= f.label :message, 'ツイート' %>
    <%= f.text_area :message, :size =>"50x5" %>
    <%= f.submit 'ツイート' %>
<% end %>
</p>